baseURL = "http://tamplin.net/"
languageCode = "en-us"
title = "James Tamplin"
theme = "hyde-hyde"

## Site Settings
[params]
    author = "James Tamplin"
    dateformat = "January 2006"
    highlightjs = true
    highlightjsstyle = "github"
    GoogleAnalyticsID = "UA-19224664-1"

## Social Accounts
[params.social]
	twitter = "jamestamplin"
	gravatar = "james@tamplin.net"
	linkedin = "jamest"

## Main Menu
##[[menu.main]]
##    name = "Posts"
##    weight = 100
##    identifier = "posts"
##    url = "/posts/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
